local client = http()
client:base_url("https://crux-pied.vercel.app")
-- client:req():url("https://example.com/health"):get()
-- client:req():path("/posts"):query("userId", "1"):get()
-- client:req():path("/posts"):queries({ userId = "1", _limit = "5" }):get()
-- client:req():path("/posts"):header("x-api-key", "secret"):get()
-- client:req():path("/posts"):headers({ ["x-api-key"] = "secret", accept = "application/json" }):get()
-- client:req():path("/posts"):timeout_ms(5000):get()
-- client:req():path("/posts"):body("plain text body"):post()
-- client:req():path("/posts"):json('{"title":"hello","body":"world","userId":1}'):post()
-- client:req():path("/posts"):form({ title = "hello", body = "world", userId = "1" }):post()
-- client:req():path("/posts/1"):bearer("token"):delete()
-- client:req():path("/posts/1"):send() -- send with current/default method

test("GET json data", function()
	local res = client
		:req()
		:path("/api/v1/getOrcr")
		:json('{"exam":"ADVANCED","year":2025,"round":6,"type":"JOSSA"}')
		:header("user-agent", "Mozilla")
		:header("sec-fetch-mode", "something")
		:header("sec-fetch-site", "something")
		:header("accept-language", "something")
		:post()
	print(res.duration_ms / 1000 .. " seconds")
end)
