local client = http()
client:base_url("https://jsonplaceholder.typicode.com")
-- test("GET /", function()
-- 	local res = client:get("/")
-- 	expect(res.status):to_equal(200)
-- end)
--
-- test("GET /explore", function()
-- 	local res = client:get("/explore")
-- 	expect(res.status):to_equal(200)
-- end)

test("GET json data", function()
	local res = client:req():path("/posts/1"):get()
	expect(res.status):to_equal(200)
	expect(res.json.id):to_equal(1)
end)
