local client = http()
client:base_url("https://crux-pied.vercel.app")

test("POST /getOrcr id test", function()
  local res = client
      :req()
      :path("/api/v1/getOrcr")
      :json('{"exam":"ADVANCED","year":2025,"round":6,"type":"JOSSA"}')
      :header("user-agent", "Mozilla")
      :header("sec-fetch-mode", "something")
      :header("sec-fetch-site", "something")
      :header("accept-language", "something")
      :post()
  expect(res.json[1].id):msg("id not matching"):to_equal("14ca23b3-36c4-49f1-82a7-763aebeb1162")
end)
