local client = http()
client:base_url("https://crux-pied.vercel.app")
-- client:req():url("https://example.com/health"):get()
-- client:req():path("/posts"):query("userId", "1"):get()
-- client:req():path("/posts"):queries({ userId = "1", _limit = "5" }):get()
-- client:req():path("/posts"):header("x-api-key", "secret"):get()
-- client:req():path("/posts"):headers({ ["x-api-key"] = "secret", accept = "application/json" }):get()
-- client:req():path("/posts"):timeout_ms(5000):get()
-- client:req():path("/posts"):body("plain text body"):post()
-- client:req():path("/posts"):json('{"title":"hello","body":"world","userId":1}'):post()
-- client:req():path("/posts"):form({ title = "hello", body = "world", userId = "1" }):post()
-- client:req():path("/posts/1"):bearer("token"):delete()
-- client:req():path("/posts/1"):send() -- send with current/default method

test("GET /getOrcr id test", function()
	local res = client
			:req()
			:path("/api/v1/getOrcr")
			:json('{"exam":"ADVANCED","year":2025,"round":6,"type":"JOSSA"}')
			:header("user-agent", "Mozilla")
			:header("sec-fetch-mode", "something")
			:header("sec-fetch-site", "something")
			:header("accept-language", "something")
			:post()
	expect(res.json[1].id):msg("id not matching"):to_equal("14ca23b3-36c4-49f1-82a7-763aebeb1162")
end)

test("GET /explore status test", function()
	local res = client:req():path("/explore"):get()

	expect(res.status):to_equal(200)
end)
